name: 'Check Commit Author'
description: 'Checks the email of the commit author'
inputs:
  email_domain:
    description: 'domain of the email'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
outputs:
  is_valid:
    description: 'returns to result whether true or false'

runs:
  using: node12
  main: dist/index.js
